pipeline {
    agent any
    stages {
        stage ('Checkout') {
            steps {
            git 'https://github.com/rajulajogendra/test.git'
                }
        }
        stage ('Build') {
        when { changeset "sandeep/*" }
            steps {
                sh "echo sandeep_Build"
            }
        }
    }
  }
