pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
            git 'https://github.com/rajulajogendra/test.git'
        }
        }
        stage('Build') {
        when { changeset "MC/*" }
            steps {
                sh "echo MC_Build "
            }
        }
    }
  }
